#!/usr/bin/env bash

set -e

for command in "$@"
do
    case "${command}" in
        unit-test)
            poetry run pytest tests/unit
        ;;
        format)
            poetry run isort demo_producer/ tests/
            poetry run black -t py310 -l100 demo_producer/ tests/
        ;;
        lint)
            poetry run flake8 demo_producer/ tests/
        ;;
        run)
            poetry run python -m demo_producer.main
        ;;
        dev-setup)
            poetry install
        ;;
        build-container)
            poetry build
            package_version=$(poetry version -s)
            git_sha=$(git rev-parse --short HEAD)
            package="demo-producer-${package_version}.tar.gz"
            docker build -t demo-producer:${git_sha} --build-arg PACKAGE=$package .
        ;;
        *)
            echo "Invalid command: '${command}'"
            exit 1
        ;;
    esac
done
